// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `fmt`, `from`

/// Day-2 smoke test — kept so the existing engine-hello status line
/// in main.dart stays green.
Future<String> engineHello() => RustLib.instance.api.crateApiEngineHello();

/// Construct the three engines from the canonical seed JSON +
/// compiled tables + a writable vault path (created at first use).
Future<EnginesHandle> constructEngines({
  required String athleteProfileJson,
  required String tablesJson,
  required String vaultPath,
}) => RustLib.instance.api.crateApiConstructEngines(
  athleteProfileJson: athleteProfileJson,
  tablesJson: tablesJson,
  vaultPath: vaultPath,
);

/// `ViterbiEngine::readiness_score()` — JSON `{"score":i32, "advisories":...}`.
Future<String> readinessScore({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiReadinessScore(handle: handle);

/// `ViterbiEngine::get_readiness()` — full snapshot JSON including
/// `fatigue_state`. gatc-ffi exposes the state through the snapshot,
/// not as a standalone scalar; Dart parses/renders as-is.
Future<String> viterbiFatigueState({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiViterbiFatigueState(handle: handle);

/// `ViterbiEngine::zone_cap_with_advisories()`.
Future<String> zoneCapWithAdvisories({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiZoneCapWithAdvisories(handle: handle);

/// `AdvisorEngine::suggest_workouts(...)`. SuggesterContext is composed
/// from (a) the engine-bound profile and (b) live `readiness_score` —
/// no per-call user input (no mood/equipment/terrain form in the
/// Day-3 UI), so those fields use defaults — see PR body.
Future<String> recommendWorkout({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiRecommendWorkout(handle: handle);

/// `VaultEngine::read_default_profile()` — round-trips the profile
/// through the on-device vault. With a fresh vault this is the seed
/// profile read back, proving write→read is live.
Future<String> vaultSnapshot({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiVaultSnapshot(handle: handle);

/// `VaultEngine::last_observation_source_tier()` — JSON `"Medical"` /
/// `"Device"` / `"Partial"` / `"Manual"` for the most recent biometric
/// observation on disk, or JSON `null` if the vault has no biometric
/// rows yet. Dart parses with `jsonDecode`; a `null` decoded value is
/// the engine's "insufficient data" signal for the SourceTier swatch.
Future<String> lastObservationSourceTier({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiLastObservationSourceTier(handle: handle);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EnginesHandle>>
abstract class EnginesHandle implements RustOpaqueInterface {}

@freezed
sealed class BridgeError with _$BridgeError implements FrbException {
  const BridgeError._();

  const factory BridgeError.libraryNotLoaded() = BridgeError_LibraryNotLoaded;
  const factory BridgeError.engineConstructionFailed(String field0) =
      BridgeError_EngineConstructionFailed;
  const factory BridgeError.vaultError(String field0) = BridgeError_VaultError;
  const factory BridgeError.inputError(String field0) = BridgeError_InputError;
  const factory BridgeError.stateError(String field0) = BridgeError_StateError;
  const factory BridgeError.roundTripFailed(String field0) =
      BridgeError_RoundTripFailed;
}
