// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `extract_athlete_id`, `readiness_assessment_fields`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AssessmentFields`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `fmt`, `fmt`, `from`

/// Day-2 smoke test — kept so the existing engine-hello status line
/// in main.dart stays green.
Future<String> engineHello() => RustLib.instance.api.crateApiEngineHello();

/// Construct all engines for a FIRST RUN (no persisted state exists).
///
/// After calling this, the Dart side MUST immediately call `save_state()`
/// and persist the returned JSON so subsequent launches can restore via
/// `construct_engines_from_state()`. The plain `new()` seed constructor is
/// only reachable here — the restore path uses `from_persisted_state()`.
Future<EnginesHandle> constructEnginesFresh({
  required String athleteProfileJson,
  required String tablesJson,
  required String vaultPath,
}) => RustLib.instance.api.crateApiConstructEnginesFresh(
  athleteProfileJson: athleteProfileJson,
  tablesJson: tablesJson,
  vaultPath: vaultPath,
);

/// Construct all engines from PERSISTED STATE (subsequent launches).
///
/// `viterbi_state_json` is the JSON returned by a prior `save_state()` call.
/// The ViterbiEngine is restored via `from_persisted_state()`, preserving the
/// learned HMM, ceiling intelligence, OutcomeTracker, etc. across app restarts.
///
/// If the state JSON is invalid or corrupted, returns an error. The Dart side
/// should handle this by falling back to `construct_engines_fresh()` and
/// accepting the state reset.
Future<EnginesHandle> constructEnginesFromState({
  required String athleteProfileJson,
  required String tablesJson,
  required String vaultPath,
  required String viterbiStateJson,
}) => RustLib.instance.api.crateApiConstructEnginesFromState(
  athleteProfileJson: athleteProfileJson,
  tablesJson: tablesJson,
  vaultPath: vaultPath,
  viterbiStateJson: viterbiStateJson,
);

/// Legacy constructor for backward compatibility with existing screens.
/// Delegates to `construct_engines_fresh`. New code should use the explicit
/// `construct_engines_fresh` / `construct_engines_from_state` pair.
Future<EnginesHandle> constructEngines({
  required String athleteProfileJson,
  required String tablesJson,
  required String vaultPath,
}) => RustLib.instance.api.crateApiConstructEngines(
  athleteProfileJson: athleteProfileJson,
  tablesJson: tablesJson,
  vaultPath: vaultPath,
);

/// `ViterbiEngine::readiness_score()` — JSON `{"score":i32, "advisories":...}`.
Future<String> readinessScore({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiReadinessScore(handle: handle);

/// `ViterbiEngine::readiness_indicator()` — the 4-axis readiness blend
/// (HMM posteriors + Banister + physio + psychological), with per-axis
/// breakdown, level, and confidence. This is the headline number for the
/// three-zone PULL home.
Future<String> readinessIndicator({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiReadinessIndicator(handle: handle);

/// `ViterbiEngine::state_advisory()` — per-state recommendation + low-confidence
/// advisory (card-sourced). Dashboard removal Phase 2: replaces the StateWidget
/// prose the home + detail read. Pure pass-through.
Future<String> stateAdvisory({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiStateAdvisory(handle: handle);

/// `ViterbiEngine::hrv_trend()` — HRV trend over short/mid/long windows
/// (descriptive direction + honest-absence; engine bands are DRAFT pending
/// ratification). Drives the Journey HRV trend surface (PR-B). Pure
/// pass-through.
Future<String> hrvTrend({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiHrvTrend(handle: handle);

/// `ViterbiEngine::rhr_trend()` — Resting-HR trend over short/mid/long windows
/// (descriptive direction + honest-absence; engine bands are DRAFT pending
/// ratification). Drives the Journey RHR trend surface (PR-B). Pure
/// pass-through.
Future<String> rhrTrend({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiRhrTrend(handle: handle);

/// `gatc_ffi::realize_advisor_line(viterbi, narrative, advisor, athlete_id, date)`
/// — the deterministic Josi ADVISOR line (Brief #6 seam). The engine assembles
/// the CommunicationPlan (viterbi) + Facts (narrative→vault) + AdvisorLines
/// (advisor), runs the fidelity firewall IN RUST, and returns a serialized
/// `RealizedLine` JSON (`text`, `safety[]`, `degraded`). `date` is supplied by
/// the caller — the engine has no clock (determinism invariant; legitimate
/// data-in, same category as cycle_day). Pure pass-through: one gatc_ffi call,
/// no logic. Fails loud (Err) when the engine cannot supply a faithful render —
/// the Dart caller treats that as honest absence and falls back to its existing
/// state-recommendation line.
Future<String> realizeAdvisorLine({
  required EnginesHandle handle,
  required String date,
}) =>
    RustLib.instance.api.crateApiRealizeAdvisorLine(handle: handle, date: date);

/// `gatc_ffi::realize_workout_reflection(vault, advisor, activity_id, date)` —
/// the S1 post-workout coach reaction (voice wiring train, engine #388). The
/// engine reads the activity + its grade from the vault, realizes through the
/// fidelity firewall, and returns `RealizedLine` JSON. Ungraded sessions get
/// the honest "logged, not judged" line — never a fabricated grade. Pure
/// pass-through; fails loud when the activity is unknown.
Future<String> realizeWorkoutReflection({
  required EnginesHandle handle,
  required String activityId,
  required String date,
}) => RustLib.instance.api.crateApiRealizeWorkoutReflection(
  handle: handle,
  activityId: activityId,
  date: date,
);

/// `gatc_ffi::realize_advisory_offer(advisor, option_json, readiness_level, date)`
/// — the S3 Josi offer line for an advisor option (voice wiring train, engine
/// #388). `option_json` is the engine's own WorkoutOption JSON couriered back
/// verbatim; `readiness_level` is the engine's readiness band token. The
/// returned `RealizedLine` carries `why`/`purpose` for the disclosure tap.
/// Pure pass-through; fails loud on an empty why (the engine refuses to offer
/// without its reason).
Future<String> realizeAdvisoryOffer({
  required EnginesHandle handle,
  required String optionJson,
  required String readinessLevel,
  required String date,
}) => RustLib.instance.api.crateApiRealizeAdvisoryOffer(
  handle: handle,
  optionJson: optionJson,
  readinessLevel: readinessLevel,
  date: date,
);

/// `gatc_ffi::realize_day_summary(vault, viterbi, advisor, date)` — the S4
/// end-of-day coach summary (voice wiring train, engine #388). The engine
/// reads the day's activities from the vault, derives the day shape
/// (rest/single/multi) from the real count, and realizes through the firewall.
/// Pure pass-through.
Future<String> realizeDaySummary({
  required EnginesHandle handle,
  required String date,
}) =>
    RustLib.instance.api.crateApiRealizeDaySummary(handle: handle, date: date);

/// `gatc_ffi::morning_read_verdict(viterbi, advisor, presence, last_state,
/// last_bucket, already_notified_today)` — BS-012 moved ENGINE-side (founder
/// decision 2026-07-06): the engine decides fire/silent and assembles the
/// card-worded `title` (never the raw state token) + `state_advisory` `body`
/// (or honestly empty). The client couriers ONLY its delivery context in
/// (presence preference, last-delivered markers, the same-day flag) and
/// schedules the OS notification out. Returns JSON `{fire, reason, state,
/// sufficiency_bucket, title, body}`. Pure pass-through; unknown presence is
/// a structured Input error.
Future<String> morningReadVerdict({
  required EnginesHandle handle,
  required String presence,
  String? lastDeliveredState,
  String? lastDeliveredBucket,
  required bool alreadyNotifiedToday,
}) => RustLib.instance.api.crateApiMorningReadVerdict(
  handle: handle,
  presence: presence,
  lastDeliveredState: lastDeliveredState,
  lastDeliveredBucket: lastDeliveredBucket,
  alreadyNotifiedToday: alreadyNotifiedToday,
);

/// `ViterbiEngine::get_acwr()` — ACWR value + zone + recommendation. Dashboard
/// removal Phase 2: replaces the ContextWidget acwr fields. Pure pass-through.
Future<String> getAcwr({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiGetAcwr(handle: handle);

/// `ViterbiEngine::get_monotony_strain()` — monotony/strain + zones + recs.
/// Dashboard removal Phase 2: replaces the ContextWidget/LoadContext monotony
/// fields. Pure pass-through.
Future<String> getMonotonyStrain({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiGetMonotonyStrain(handle: handle);

/// `ViterbiEngine::pending_advisories()` — reactive alerts + pattern advisories.
/// Dashboard removal Phase 2: replaces the ContextWidget alert lists. Pure
/// pass-through.
Future<String> pendingAdvisories({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiPendingAdvisories(handle: handle);

/// `VaultEngine::last_workout_summary()` — one-line narrative summary of the most
/// recent activity (empty when none). Dashboard removal Phase 2: replaces the
/// ContextWidget `last_workout` string. Pure pass-through.
Future<String> lastWorkoutSummary({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiLastWorkoutSummary(handle: handle);

/// `ViterbiEngine::get_readiness()` — full snapshot JSON including
/// `fatigue_state`. gatc-ffi exposes the state through the snapshot,
/// not as a standalone scalar; Dart parses/renders as-is.
Future<String> viterbiFatigueState({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiViterbiFatigueState(handle: handle);

/// `ViterbiEngine::validation_report()` — on-device prediction-vs-reality
/// validation. JSON `ValidationReport`: `data_sufficiency`
/// (insufficient|low|medium|high), `paired_observations`, `period_days`,
/// `overall_model_score`, and the nested accuracy breakdowns. Drives the
/// honest "is the model validated for YOU yet" surface. Pure transport.
Future<String> validationReport({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiValidationReport(handle: handle);

/// `ViterbiEngine::personalization_diagnostics()` — learning-progress
/// diagnostics: `observation_count` (toward the population→personal handover),
/// `confidence` bucket (low|medium|high), and the optional multi-scale HRV
/// windows / episode classification. JSON `null` until the first observation.
/// Pure transport.
Future<String> personalizationDiagnostics({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiPersonalizationDiagnostics(handle: handle);

/// `ViterbiEngine::zone_cap_with_advisories()`.
Future<String> zoneCapWithAdvisories({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiZoneCapWithAdvisories(handle: handle);

/// `ViterbiEngine::save_state()` — serialize the current HMM state to JSON.
/// Call this after any state-changing operation and persist the result to
/// the vault via `write_viterbi_state()`. On next launch, pass this JSON
/// to `construct_engines_from_state()` to restore continuity.
Future<String> saveState({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiSaveState(handle: handle);

/// `ViterbiEngine::pause_learning()` — V4 global privacy setting: stop ALL
/// model mutation (baselines, windows, transitions). The engine still reads
/// state; it learns nothing while paused. Pure transport (4b-ii).
Future<void> pauseLearning({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiPauseLearning(handle: handle);

/// `ViterbiEngine::resume_learning()` — lift the V4 privacy pause.
Future<void> resumeLearning({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiResumeLearning(handle: handle);

/// `ViterbiEngine::is_learning_paused()` — read the V4 pause flag for the
/// Settings toggle.
Future<bool> isLearningPaused({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiIsLearningPaused(handle: handle);

/// `ViterbiEngine::process_observation(observation_json)` — feed a
/// UniversalObservation (JSON) to the HMM. Returns the updated assessment
/// JSON including fatigue_state, readiness_level, confidence, etc.
///
/// Use this for vendor-normalized observations (from [normalizeObservation]).
/// For manual entry, prefer [processManualObservation] which builds the
/// typed observation in Rust with proper defaults.
Future<String> processObservation({
  required EnginesHandle handle,
  required String observationJson,
}) => RustLib.instance.api.crateApiProcessObservation(
  handle: handle,
  observationJson: observationJson,
);

/// Build and process a manual observation entry in Rust.
///
/// This helper constructs a typed [UniversalObservation] with `source="manual"`
/// and `tier=Minimal`, then processes it through the HMM. Keeps JSON hand-building
/// out of Dart and ensures honest provenance.
///
/// `iso_date` must parse as `YYYY-MM-DD`; returns [BridgeError::InvalidDate] if not.
/// All biometric fields are optional; pass `None` for fields the user didn't enter.
Future<String> processManualObservation({
  required EnginesHandle handle,
  required String isoDate,
  double? restingHr,
  double? hrvRmssd,
  double? sleepHours,
  int? rpe,
}) => RustLib.instance.api.crateApiProcessManualObservation(
  handle: handle,
  isoDate: isoDate,
  restingHr: restingHr,
  hrvRmssd: hrvRmssd,
  sleepHours: sleepHours,
  rpe: rpe,
);

/// `gatc_ffi::build_onboarding_profile(...)` — PURE TRANSPORT (FL-16).
///
/// Stateless: onboarding has no engine instance yet. The client marshals the
/// RAW onboarding inputs into `inputs_json` and the ENGINE derives everything
/// (`goal_class`, the mesocycle + availability + `meso_minutes`, per-sport
/// anchor gating). The client computes nothing.
Future<String> buildOnboardingProfile({required String inputsJson}) =>
    RustLib.instance.api.crateApiBuildOnboardingProfile(inputsJson: inputsJson);

/// `AdvisorEngine::recommend_workout(...)` — PURE TRANSPORT (FL-1).
///
/// The shim forwards the engine's OWN readiness signals to the engine, which
/// owns ALL coaching mapping (readiness band, confidence tier, periodization):
/// `readiness_indicator()` supplies the blended score, the canonical
/// traffic-light `level` (green/yellow/orange/red) and the posterior
/// `confidence`; `get_readiness()` supplies the decided fatigue `state`. The
/// shim no longer thresholds the score, buckets confidence, invents
/// periodization, or defaults to a green-ish state on no data — a missing
/// engine field is an error, not a fabricated value.
///
/// `date`: a "what should I do now" recommendation legitimately needs today's
/// date. It is taken as UTC, so there is no timezone non-determinism (the old
/// `Local::now()` had both). Passing the user's local date down from the Dart
/// display layer is a follow-up that requires an FRB binding regen.
Future<String> recommendWorkout({
  required EnginesHandle handle,
  String? mood,
  String? equipment,
  String? terrain,
}) => RustLib.instance.api.crateApiRecommendWorkout(
  handle: handle,
  mood: mood,
  equipment: equipment,
  terrain: terrain,
);

/// `AdvisorEngine::recommend_workout_with_history(...)` — PURE TRANSPORT.
///
/// The Phase-2 tail (GATC roadmap): identical to [`recommend_workout`] plus the
/// recent completed-activity window, so the engine can rotate the PRIMARY option
/// toward the athlete's most-needed energy system (`TrainingState`, 6-system
/// model). The shim reads `VaultEngine::read_recent_activities` and forwards the
/// raw JSON untouched — the engine parses it, classifies each session by
/// (zone, duration), diffs against the card-driven phase target, and applies the
/// card-driven rotation gate. Zero coaching logic here.
///
/// The 14-row window mirrors the existing shim precedent
/// (`recent_decoupling_pct(14)`): it transports a documented window size, not a
/// policy — the actionability gate (min sessions / min deficit) lives in the
/// engine's `phase_energy_system_signatures:rotation_gate` card.
Future<String> recommendWorkoutWithHistory({
  required EnginesHandle handle,
  String? mood,
  String? equipment,
  String? terrain,
}) => RustLib.instance.api.crateApiRecommendWorkoutWithHistory(
  handle: handle,
  mood: mood,
  equipment: equipment,
  terrain: terrain,
);

/// `VaultEngine::write_assessment(...)` — the #3 readiness write-back (go-live).
///
/// Persists the engine's CURRENT 4-axis readiness indicator (+ Viterbi fatigue state)
/// to `date`'s biometrics readiness columns, so the Journey charts read it back
/// (`read_readiness_history`, filtered `WHERE readiness_score IS NOT NULL`).
/// `write_assessment` is the SINGLE writer of those columns (#298), so this no
/// longer races `write_biometric`.
///
/// Courier-not-computer: the shim reads the engine's own values and writes them
/// back, computing nothing. The only decision is the honest-absence skip, owned
/// here in Rust (NOT in Dart) via [`readiness_assessment_fields`]. Returns `true`
/// if a row was written, `false` if skipped on honest absence — Dart only couriers
/// the date.
Future<bool> writeReadinessAssessment({
  required EnginesHandle handle,
  required String date,
}) => RustLib.instance.api.crateApiWriteReadinessAssessment(
  handle: handle,
  date: date,
);

/// `VaultEngine::read_default_profile()` — round-trips the profile
/// through the on-device vault. With a fresh vault this is the seed
/// profile read back, proving write→read is live.
Future<String> vaultSnapshot({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiVaultSnapshot(handle: handle);

/// `VaultEngine::last_observation_source_tier()` — JSON `"Medical"` /
/// `"Device"` / `"Partial"` / `"Manual"` for the most recent biometric
/// observation on disk, or JSON `null` if the vault has no biometric
/// rows yet. Dart parses with `jsonDecode`; a `null` decoded value is
/// the engine's "insufficient data" signal for the SourceTier swatch.
Future<String> lastObservationSourceTier({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiLastObservationSourceTier(handle: handle);

/// `VaultEngine::read_readiness_history(days)` — series of readiness
/// snapshots for the past N days, driving the home/detail trend chart.
Future<String> readReadinessHistory({
  required EnginesHandle handle,
  required int days,
}) => RustLib.instance.api.crateApiReadReadinessHistory(
  handle: handle,
  days: days,
);

/// `VaultEngine::read_daily_loads(days)` — daily training load (`load_uls`
/// summed per day) for the past N days, JSON `[[date, load], ...]`. Drives the
/// Monitor training-load surface. Pure pass-through.
Future<String> readDailyLoads({
  required EnginesHandle handle,
  required int days,
}) => RustLib.instance.api.crateApiReadDailyLoads(handle: handle, days: days);

/// `VaultEngine::read_activities_in_range(start, end)` — every stored activity
/// in the closed date window (`yyyy-MM-dd`), JSON array, pageable arbitrarily
/// far back. Drives the Journey history list ("open ANY past workout" — PR-B).
/// Pure pass-through; the engine parses and validates the dates.
Future<String> readActivitiesInRange({
  required EnginesHandle handle,
  required String start,
  required String end,
}) => RustLib.instance.api.crateApiReadActivitiesInRange(
  handle: handle,
  start: start,
  end: end,
);

/// `VaultEngine::metabolic_time_in_zone_rollup(start, end)` — the per-window
/// time-in-metabolic-level rollup (week/meso recall), summed by the ENGINE
/// from stored per-workout atoms. JSON per the progression data-model
/// contract. Drives the Journey energy-recall surface (PR-B). Pure
/// pass-through — the sum happens engine-side, never in Dart (Law 2).
Future<String> metabolicTimeInZoneRollup({
  required EnginesHandle handle,
  required String start,
  required String end,
}) => RustLib.instance.api.crateApiMetabolicTimeInZoneRollup(
  handle: handle,
  start: start,
  end: end,
);

/// `VaultEngine::import_encrypted_vault(...)` — restore a `.mvbackup` blob
/// (V5 encrypted export's inverse). The engine owns decryption, validation,
/// and the overwrite decision; a wrong passphrase fails loud, never a partial
/// import. Closes the export-without-import half-truth (PR-B). Pure
/// pass-through.
Future<String> importEncryptedVault({
  required EnginesHandle handle,
  required String athleteId,
  required String passphrase,
  required List<int> blob,
  required bool overwrite,
}) => RustLib.instance.api.crateApiImportEncryptedVault(
  handle: handle,
  athleteId: athleteId,
  passphrase: passphrase,
  blob: blob,
  overwrite: overwrite,
);

/// `VaultEngine::read_mmp_history(athlete_id)` — the rolling mean-maximal power
/// curve, JSON `{"points":[{"duration_seconds","max_power_watts"}...]}` or
/// `null`. Drives the Monitor power-profile surface. Pure pass-through.
Future<String> readMmpHistory({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiReadMmpHistory(handle: handle);

/// `PostProcessEngine::compute_time_in_zone(activity_json)` — per-zone dwell
/// for one completed activity, binned through MiValta's own `zone_anchors`
/// scale (R, Z1..Z8). `activity_json` is the producer-pipeline activity wire
/// (`{"completed_at","power_samples":[..],"hr_samples":[..]?,"sample_rate_hz"}`).
/// Returns `TimeInZone {anchor, seconds:[{zone,seconds}×9], total_seconds}`
/// JSON. The engine picks the anchor from the bound profile (cycling+FTP+power
/// → power, else HR) and errors when neither anchor is usable. Pure pass-through.
Future<String> computeTimeInZone({
  required EnginesHandle handle,
  required String activityJson,
}) => RustLib.instance.api.crateApiComputeTimeInZone(
  handle: handle,
  activityJson: activityJson,
);

/// `CpEngine::fit_cp_default(mmp_curve_json)` — Critical Power + W′ fit over an
/// MMP curve (Monod-Scherrer 1965 / Hill 1993). Feed the same curve JSON
/// `read_mmp_history` returns; yields `CpFit{cp_watts, w_prime_joules,
/// r_squared, n_points}`. Pure pass-through. Monitor power-profile depth.
Future<String> fitCp({
  required EnginesHandle handle,
  required String mmpCurveJson,
}) => RustLib.instance.api.crateApiFitCp(
  handle: handle,
  mmpCurveJson: mmpCurveJson,
);

/// `VaultEngine::read_recent_activities(limit)` — most recent completed
/// activities (newest first), JSON array of stored activities. Used to find the
/// latest workout's date for the workout-detail surface. Pure pass-through.
Future<String> readRecentActivities({
  required EnginesHandle handle,
  required int limit,
}) => RustLib.instance.api.crateApiReadRecentActivities(
  handle: handle,
  limit: limit,
);

/// `VaultEngine::write_activity(activity_json)` — persist a completed activity
/// to the vault. The activity JSON is `VaultActivity` (must include `completed_at`,
/// `activity_type`, `duration_minutes`, `load_uls`, `load_method`).
/// Pure pass-through. Activity ingestion flow (Recipe 4, step 1).
Future<void> writeActivity({
  required EnginesHandle handle,
  required String activityJson,
}) => RustLib.instance.api.crateApiWriteActivity(
  handle: handle,
  activityJson: activityJson,
);

/// `PostProcessEngine::process_activity(...)` — run the post-activity producer
/// pipeline on a completed activity. Takes:
/// - `activity_json`: `{"completed_at": "<rfc3339>", "power_samples": [..], "hr_samples": [..]?, "sample_rate_hz": 1.0}`
/// - `history_json`: prior `MmpHistory` (use `{"points": []}` on first run)
/// - `current_fit_json`: prior `{"cp_watts":..,"w_prime_joules":..}` or `"null"`
/// - `policy_json`: serialized `PostProcessPolicy` (defaults_v0 shape)
///
/// Returns `PostProcessResult` JSON: mmp_after, power_profile_update?, wbal_series?, decoupling?, events.
/// Pure pass-through. Activity ingestion flow (Recipe 4, step 3).
Future<String> processActivity({
  required EnginesHandle handle,
  required String activityJson,
  required String historyJson,
  required String currentFitJson,
  required String policyJson,
}) => RustLib.instance.api.crateApiProcessActivity(
  handle: handle,
  activityJson: activityJson,
  historyJson: historyJson,
  currentFitJson: currentFitJson,
  policyJson: policyJson,
);

/// `VaultEngine::read_power_profile(athlete_id)` — read the persisted PowerProfile
/// (CP, W', fit metadata). Returns JSON `null` if no profile saved (no CP test yet).
/// Pure pass-through. Activity ingestion flow (Recipe 4, step 2).
Future<String> readPowerProfile({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiReadPowerProfile(handle: handle);

/// `VaultEngine::write_power_profile(athlete_id, profile_json)` — persist the
/// athlete's PowerProfile after a CP refit. Pure pass-through. Activity ingestion
/// flow (Recipe 4, step 4).
Future<void> writePowerProfile({
  required EnginesHandle handle,
  required String profileJson,
}) => RustLib.instance.api.crateApiWritePowerProfile(
  handle: handle,
  profileJson: profileJson,
);

/// `VaultEngine::write_mmp_history(athlete_id, history_json)` — persist the rolling
/// MMP curve history after process_activity. Pure pass-through. Activity ingestion
/// flow (Recipe 4, step 4).
Future<void> writeMmpHistory({
  required EnginesHandle handle,
  required String historyJson,
}) => RustLib.instance.api.crateApiWriteMmpHistory(
  handle: handle,
  historyJson: historyJson,
);

/// `ViterbiEngine::record_activity(load_json)` — tell the HMM that a training load
/// happened. `load_json` is `UniversalLoadScore` JSON. Updates internal state; call
/// `save_state()` afterward to persist. Pure pass-through. Activity ingestion flow
/// (Recipe 4, step 5).
Future<void> recordActivity({
  required EnginesHandle handle,
  required String loadJson,
}) => RustLib.instance.api.crateApiRecordActivity(
  handle: handle,
  loadJson: loadJson,
);

/// `VaultEngine::get_workout_detail(date)` — completed-workout detail composite
/// (actuals + engine-graded quality via `grade_workout`) for a date. JSON
/// matches the Flutter `WorkoutDetail` contract, or JSON `null` when no activity
/// on that date. Pure pass-through. Monitor workout-detail surface.
Future<String> getWorkoutDetail({
  required EnginesHandle handle,
  required String date,
}) => RustLib.instance.api.crateApiGetWorkoutDetail(handle: handle, date: date);

/// `VaultEngine::realize_benchmark_change(event_json)` — compose the Phase 3
/// notify card from a `benchmark_change` event ("your threshold improved").
/// Pass the `event` from `sync_benchmark_from_activities`, or the
/// `assessment_json` of a `benchmark_change` ledger row. Returns
/// `{kind, headline, benchmark_line, disclosure:[…]}` (engine-composed,
/// unit-correct) or the string `"null"` on an absent/unknown event. Pure
/// pass-through; the engine composes every word.
Future<String> realizeBenchmarkChange({
  required EnginesHandle handle,
  required String eventJson,
}) => RustLib.instance.api.crateApiRealizeBenchmarkChange(
  handle: handle,
  eventJson: eventJson,
);

/// `VaultEngine::read_audit_trail(athlete_id, event_type, plan_id, limit)` —
/// the athlete's audit ledger, newest first, optionally filtered by event
/// type (empty = all). Used to read the latest `benchmark_change` row for the
/// notify card. Returns a JSON array of audit entries. Pure pass-through.
Future<String> readAuditTrail({
  required EnginesHandle handle,
  required String eventType,
  required int limit,
}) => RustLib.instance.api.crateApiReadAuditTrail(
  handle: handle,
  eventType: eventType,
  limit: limit,
);

/// `VaultEngine::completed_workout_facts(date)` — assembles the post-workout
/// report's INPUT facts (engine-classified zone + actuals + quality) for a date.
/// JSON `CompletedWorkoutFacts`, or `null` when no activity. Pair with
/// `build_post_workout_report`. Pure pass-through. Advisor post-workout surface.
Future<String> completedWorkoutFacts({
  required EnginesHandle handle,
  required String date,
}) => RustLib.instance.api.crateApiCompletedWorkoutFacts(
  handle: handle,
  date: date,
);

/// `AdvisorEngine::build_post_workout_report(facts_json)` — card-grounded report
/// (energy system, zone purpose, stimulus/cost note, quality summary, autocue)
/// resolved against the bound ruleset. Feed the JSON `completed_workout_facts`
/// returns. Pure pass-through. Advisor post-workout surface.
Future<String> buildPostWorkoutReport({
  required EnginesHandle handle,
  required String factsJson,
}) => RustLib.instance.api.crateApiBuildPostWorkoutReport(
  handle: handle,
  factsJson: factsJson,
);

/// `VaultEngine::read_biometric_history(days)` — daily biometric snapshots for
/// the past N days, JSON array incl. `sleep_hours` / `sleep_quality`. Drives the
/// Monitor sleep-trend surface. Pure pass-through.
Future<String> readBiometricHistory({
  required EnginesHandle handle,
  required int days,
}) => RustLib.instance.api.crateApiReadBiometricHistory(
  handle: handle,
  days: days,
);

/// `VaultEngine::recent_decoupling_pct(window_days)` — trailing-window mean of
/// `hr_decoupling_pct` across completed activities, JSON
/// `{"mean_decoupling_pct": <f64|null>}` (null when no reading in the window).
/// Drives the Monitor aerobic-decoupling surface. Pure pass-through.
Future<String> recentDecouplingPct({
  required EnginesHandle handle,
  required int windowDays,
}) => RustLib.instance.api.crateApiRecentDecouplingPct(
  handle: handle,
  windowDays: windowDays,
);

/// `ViterbiEngine::fitness_series(days)` — long-term Banister fitness *trend*
/// (the slow shape), JSON `[{date, fitness, fatigue, form}]` ascending by date.
/// Distinct from the HMM *state*. Pure pass-through.
Future<String> fitnessSeries({
  required EnginesHandle handle,
  required int days,
}) => RustLib.instance.api.crateApiFitnessSeries(handle: handle, days: days);

/// `VaultEngine::read_metric_across_activities(metric, activity_type, limit)` —
/// dated per-activity metric series for the fitness-trend actuals overlay
/// (e.g. `normalized_power`, `pace_sec_per_km`). JSON array of `MetricPoint`.
/// Pure pass-through.
Future<String> readMetricAcrossActivities({
  required EnginesHandle handle,
  required String metric,
  required String activityType,
  required int limit,
}) => RustLib.instance.api.crateApiReadMetricAcrossActivities(
  handle: handle,
  metric: metric,
  activityType: activityType,
  limit: limit,
);

/// `VaultEngine::write_viterbi_state(athlete_id, json)` — persist the
/// ViterbiEngine state to the vault. Call this after `save_state()` to
/// ensure continuity across app restarts.
Future<void> writeViterbiState({
  required EnginesHandle handle,
  required String stateJson,
}) => RustLib.instance.api.crateApiWriteViterbiState(
  handle: handle,
  stateJson: stateJson,
);

/// `VaultEngine::read_viterbi_state(athlete_id)` — read the persisted
/// ViterbiEngine state from the vault. Returns JSON `null` if no state
/// exists (first run). Use this at launch to check whether to call
/// `construct_engines_from_state()` or `construct_engines_fresh()`.
Future<String> readViterbiState({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiReadViterbiState(handle: handle);

/// `PostProcessEngine::sync_benchmark_from_activities` — the CLOSED benchmark
/// loop (rust-engine registry v2.42): raw activity streams → merged
/// best-effort curve → sport-native fit (CP watts for cyclists, Critical
/// Speed for runners) → confirm/promote gate over the remembered evidence
/// window → the decision APPLIED to the engine's bound profile. The engine
/// derives `today` from the device clock here in the shim (same precedent as
/// `advisor_options`' `today_iso` — the caller supplies the real current
/// date; the engine itself stays clock-free).
///
/// `activities_json`: `[{"samples":[f64…],"sample_rate_hz":1.0}]` — watts for
/// a cyclist, metres/second for a runner (the athlete's own unit; never
/// crossed). `candidate_history_json`: what `read_benchmark_history`
/// returned (`"null"` on first run).
///
/// Returns `{decision, applied, event|null, candidate_history,
/// athlete_profile}`. Dart's courier duties, all verbatim: persist
/// `athlete_profile` (write_profile + update_profile), store
/// `candidate_history` (write_benchmark_history), file `event`
/// (write_benchmark_event) when present.
Future<String> syncBenchmarkFromActivities({
  required EnginesHandle handle,
  required String activitiesJson,
  required String candidateHistoryJson,
}) => RustLib.instance.api.crateApiSyncBenchmarkFromActivities(
  handle: handle,
  activitiesJson: activitiesJson,
  candidateHistoryJson: candidateHistoryJson,
);

/// `VaultEngine::write_benchmark_event(athlete_id, event_json)` — file a
/// benchmark promotion/demotion in the encrypted audit ledger
/// (`event_type = "benchmark_change"`). Pass the `event` object from
/// `sync_benchmark_from_activities` VERBATIM; the vault validates every
/// field and composes the human message engine-side. Returns
/// `{"audit_id": "…"}`.
Future<String> writeBenchmarkEvent({
  required EnginesHandle handle,
  required String eventJson,
}) => RustLib.instance.api.crateApiWriteBenchmarkEvent(
  handle: handle,
  eventJson: eventJson,
);

/// `VaultEngine::write_benchmark_history(athlete_id, history_json)` — persist
/// the benchmark pattern memory (the `candidate_history` the sync returned),
/// VERBATIM, athlete-keyed like `write_viterbi_state`.
Future<void> writeBenchmarkHistory({
  required EnginesHandle handle,
  required String historyJson,
}) => RustLib.instance.api.crateApiWriteBenchmarkHistory(
  handle: handle,
  historyJson: historyJson,
);

/// `VaultEngine::read_benchmark_history(athlete_id)` — read the persisted
/// pattern memory, or the string `"null"` on first run (honest absence the
/// sync seam accepts as an empty evidence window).
Future<String> readBenchmarkHistory({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiReadBenchmarkHistory(handle: handle);

/// `PostProcessEngine::profile()` — the athlete profile AS THE LIVE ENGINE
/// HOLDS IT. After `sync_benchmark_from_activities` applies a promotion,
/// THIS is the byte-exact source Dart persists and re-binds from — never a
/// Dart re-assembly of the sync payload (Law 2).
Future<String> postprocessProfile({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiPostprocessProfile(handle: handle);

/// Minimal biometric write for the hardware-verification debug swatch
/// exerciser. Composes a minimal VaultBiometric JSON with `date`,
/// `source`, and a placeholder `resting_hr` so the next
/// `last_observation_source_tier` call returns the matching tier and
/// the readiness screen's section (e) picks up the LOCKED swatch.
///
/// `iso_date` must parse as `YYYY-MM-DD`; on failure the shim emits
/// `BridgeError::InvalidDate` *before* touching the vault.
Future<void> writeMinimalBiometric({
  required EnginesHandle handle,
  required String source,
  required String isoDate,
  required int restingHr,
}) => RustLib.instance.api.crateApiWriteMinimalBiometric(
  handle: handle,
  source: source,
  isoDate: isoDate,
  restingHr: restingHr,
);

/// `VaultEngine::write_raw_observation(json)` — persist raw vendor observation
/// BEFORE processing. Returns the row ID for later `mark_raw_observation_processed`.
/// JSON must include `date`, `source`, `data_type`, and `payload` fields.
Future<PlatformInt64> writeRawObservation({
  required EnginesHandle handle,
  required String json,
}) => RustLib.instance.api.crateApiWriteRawObservation(
  handle: handle,
  json: json,
);

/// `VaultEngine::write_biometric(json)` — persist a normalized biometric
/// observation (VaultBiometric JSON: date, source, resting_hr, hrv_rmssd,
/// sleep_hours, sleep_quality, etc.). Call this after normalizeObservation
/// to persist the biometrics to the vault for the Journey biometric pillars.
Future<void> writeBiometric({
  required EnginesHandle handle,
  required String json,
}) => RustLib.instance.api.crateApiWriteBiometric(handle: handle, json: json);

/// `VaultEngine::write_biometric_from_observation(json)` — persist a biometric
/// row from a normalized observation (`UniversalObservation` JSON, the
/// `normalizeObservation` output). The engine converts the observation shape
/// (`resting_hr` f64, engine-internal fields) to the vault row shape
/// (`resting_hr` i32, `sleep_quality` categorical String). Use this on the
/// ingest path — handing `normalizeObservation`'s output straight to
/// `write_biometric` fails on the type mismatch (float `resting_hr` → i32).
Future<void> writeBiometricFromObservation({
  required EnginesHandle handle,
  required String json,
}) => RustLib.instance.api.crateApiWriteBiometricFromObservation(
  handle: handle,
  json: json,
);

/// `VaultEngine::mark_raw_observation_processed(id, observation_json)` — flag
/// a raw observation as processed after the pipeline consumed it. Stores the
/// normalized `UniversalObservation` JSON alongside the raw payload (pass empty
/// string to skip storing the normalized form).
Future<void> markRawObservationProcessed({
  required EnginesHandle handle,
  required PlatformInt64 id,
  required String observationJson,
}) => RustLib.instance.api.crateApiMarkRawObservationProcessed(
  handle: handle,
  id: id,
  observationJson: observationJson,
);

/// `VaultEngine::read_raw_observations_by_type(data_type, days)` — fetch raw
/// observations for a data type (e.g. "biometric", "activity") over the last N
/// days. Returns JSON array of raw observation records.
Future<String> readRawObservationsByType({
  required EnginesHandle handle,
  required String dataType,
  required int days,
}) => RustLib.instance.api.crateApiReadRawObservationsByType(
  handle: handle,
  dataType: dataType,
  days: days,
);

/// `VaultEngine::read_raw_observations_by_activity(activity_id)` — fetch raw
/// observations linked to a specific activity ID. Returns JSON array.
Future<String> readRawObservationsByActivity({
  required EnginesHandle handle,
  required String activityId,
}) => RustLib.instance.api.crateApiReadRawObservationsByActivity(
  handle: handle,
  activityId: activityId,
);

/// `VaultEngine::read_activity_by_id(activity_id)` — fetch a single stored
/// activity by its ID. Returns JSON of the VaultActivity or error if not found.
Future<String> readActivityById({
  required EnginesHandle handle,
  required String activityId,
}) => RustLib.instance.api.crateApiReadActivityById(
  handle: handle,
  activityId: activityId,
);

/// Update the athlete profile across all engines.
///
/// This re-binds the profile in ViterbiEngine, AdvisorEngine, and
/// NormalizerEngine. The Vault profile is updated via `write_profile`.
/// Call this when the user edits their profile in Settings.
Future<void> updateProfile({
  required EnginesHandle handle,
  required String athleteProfileJson,
}) => RustLib.instance.api.crateApiUpdateProfile(
  handle: handle,
  athleteProfileJson: athleteProfileJson,
);

/// Persist the profile to the encrypted vault.
///
/// This writes a VaultProfile record to vault.db (SQLCipher-encrypted).
/// The profile is retrievable via `read_default_profile()`.
Future<void> writeProfile({
  required EnginesHandle handle,
  required String json,
}) => RustLib.instance.api.crateApiWriteProfile(handle: handle, json: json);

/// Persist a benchmark promotion into the athlete's stored profile.
///
/// Pure pass-through to `VaultEngine::merge_profile_benchmarks`, which owns the
/// merge rule: read the stored `VaultProfile`, overwrite only the coaching
/// anchors (FTP / threshold pace / threshold HR / cycling power profile), keep
/// `athlete_id` + personal data, fail loud if no profile exists. The correct
/// replacement for the silent-loss `write_profile(postprocessProfile())` path —
/// a bare `AthleteProfile` (no `athlete_id`) the `VaultProfile` writer
/// serde-rejected, so promotions never reached the vault.
Future<void> mergeProfileBenchmarks({
  required EnginesHandle handle,
  required String athleteProfileJson,
}) => RustLib.instance.api.crateApiMergeProfileBenchmarks(
  handle: handle,
  athleteProfileJson: athleteProfileJson,
);

/// Read the default profile from the vault.
///
/// Returns the JSON-serialized VaultProfile, or error if none exists.
Future<String> readDefaultProfile({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiReadDefaultProfile(handle: handle);

/// Export the entire vault as an encrypted backup blob.
///
/// The blob is passphrase-encrypted (AES-256-GCM) and safe to store anywhere.
/// Without the passphrase, the data is unrecoverable. By design.
///
/// `passphrase` must score ≥50 on strength check or returns InputError.
/// Returns the raw encrypted bytes — Dart saves to a file via share sheet.
Future<Uint8List> exportEncryptedVault({
  required EnginesHandle handle,
  required String athleteId,
  required String passphrase,
}) => RustLib.instance.api.crateApiExportEncryptedVault(
  handle: handle,
  athleteId: athleteId,
  passphrase: passphrase,
);

/// Export biometric history as CSV.
///
/// Returns CSV content as a string (date,resting_hr,hrv_rmssd,...).
/// `days` controls how many days of history (0 = all).
/// The Dart side saves this to a file via the platform share sheet.
Future<String> exportBiometricsCsv({
  required EnginesHandle handle,
  required int days,
}) => RustLib.instance.api.crateApiExportBiometricsCsv(
  handle: handle,
  days: days,
);

/// Permanently erase all user data.
///
/// This destroys the vault key → all encrypted data becomes unrecoverable noise.
/// Also calls `crypto_erase_cache()` to wipe the sealed cache key.
///
/// Returns a JSON `ClearAllUserDataReport` documenting what was destroyed
/// (row counts, bundle counts, etc.) for the confirmation receipt.
///
/// **IRREVERSIBLE.** Dart must show a confirm dialog before calling.
Future<String> clearAllUserData({
  required EnginesHandle handle,
  required String athleteId,
}) => RustLib.instance.api.crateApiClearAllUserData(
  handle: handle,
  athleteId: athleteId,
);

/// Cryptographically erase only the sealed cache key.
///
/// After this, any sealed cache backups are unrecoverable noise.
/// The main vault is unaffected. Use `clear_all_user_data` to wipe everything.
Future<void> cryptoEraseCache({required EnginesHandle handle}) =>
    RustLib.instance.api.crateApiCryptoEraseCache(handle: handle);

/// `NormalizerEngine::normalize_observation(vendor, json)` — normalize
/// vendor-specific observation JSON to a UniversalObservation.
///
/// Supported vendors: garmin, oura, whoop, polar, apple/healthkit,
/// wahoo, coros, ble. The engine bounds-validates the result before
/// returning. The Dart side receives a normalized JSON ready to pass
/// to `ViterbiEngine::process_observation()`.
Future<String> normalizeObservation({
  required EnginesHandle handle,
  required String vendor,
  required String json,
}) => RustLib.instance.api.crateApiNormalizeObservation(
  handle: handle,
  vendor: vendor,
  json: json,
);

/// `NormalizerEngine::classify_source(source)` — classify a data source
/// into a quality tier. Returns JSON with tier, tier_code, and
/// confidence_acceleration.
Future<String> classifySource({
  required EnginesHandle handle,
  required String source,
}) =>
    RustLib.instance.api.crateApiClassifySource(handle: handle, source: source);

/// `NormalizerEngine::build_source_overview(sources_json)` — build a
/// complete "data sources overview" for the mobile UI. Returns which
/// source is primary for each metric (HRV, sleep, RHR, activity).
Future<String> buildSourceOverview({
  required EnginesHandle handle,
  required String sourcesJson,
}) => RustLib.instance.api.crateApiBuildSourceOverview(
  handle: handle,
  sourcesJson: sourcesJson,
);

/// Check if a persisted ViterbiEngine state exists for the given athlete.
/// Uses a temporary VaultEngine to query without constructing all engines.
///
/// Returns `true` if state exists and should be restored via
/// `construct_engines_from_state()`, `false` if this is a first run and
/// should use `construct_engines_fresh()`.
Future<bool> hasPersistedState({
  required String athleteProfileJson,
  required String vaultPath,
}) => RustLib.instance.api.crateApiHasPersistedState(
  athleteProfileJson: athleteProfileJson,
  vaultPath: vaultPath,
);

/// Read the persisted ViterbiEngine state JSON directly from the vault.
/// Returns `None` if no state exists (first run), `Some(json)` otherwise.
/// Use this to get the state JSON to pass to `construct_engines_from_state()`.
Future<String?> readPersistedState({
  required String athleteProfileJson,
  required String vaultPath,
}) => RustLib.instance.api.crateApiReadPersistedState(
  athleteProfileJson: athleteProfileJson,
  vaultPath: vaultPath,
);

/// Read the athlete profile from the encrypted vault using just the athlete_id.
///
/// Bootstrap approach: the Dart side persists only the athlete_id (a random UUID)
/// in plaintext; the full profile (age/sex/FTP/anchors) lives in the encrypted
/// vault. On app launch, Dart calls this function with just the athlete_id to
/// retrieve the full profile JSON.
///
/// Returns `None` if no profile exists in the vault (first run scenario).
/// Returns `Some(profile_json)` if a profile was found.
///
/// The bootstrap profile used internally has placeholder values for all fields
/// except athlete_id — these placeholders are never used because `read_default_profile`
/// reads from the vault DB, not from the construction-time profile.
Future<String?> readProfileFromVault({
  required String athleteId,
  required String vaultPath,
}) => RustLib.instance.api.crateApiReadProfileFromVault(
  athleteId: athleteId,
  vaultPath: vaultPath,
);

/// Write the athlete profile to the encrypted vault.
///
/// Use this after onboarding to persist the full profile. The profile is
/// encrypted at rest (AES-256-GCM via SQLCipher).
///
/// This is a standalone function for first-run bootstrap — after engines are
/// constructed, use `write_profile(handle, json)` instead.
Future<void> writeProfileToVault({
  required String athleteProfileJson,
  required String vaultPath,
}) => RustLib.instance.api.crateApiWriteProfileToVault(
  athleteProfileJson: athleteProfileJson,
  vaultPath: vaultPath,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EnginesHandle>>
abstract class EnginesHandle implements RustOpaqueInterface {}

@freezed
sealed class BridgeError with _$BridgeError implements FrbException {
  const BridgeError._();

  const factory BridgeError.libraryNotLoaded() = BridgeError_LibraryNotLoaded;
  const factory BridgeError.engineConstructionFailed(String field0) =
      BridgeError_EngineConstructionFailed;
  const factory BridgeError.vaultError(String field0) = BridgeError_VaultError;
  const factory BridgeError.inputError(String field0) = BridgeError_InputError;
  const factory BridgeError.stateError(String field0) = BridgeError_StateError;
  const factory BridgeError.roundTripFailed(String field0) =
      BridgeError_RoundTripFailed;

  /// ISO-8601 date string couldn't be parsed at the shim before
  /// reaching the engine. Distinct from `InputError` so the debug
  /// exerciser (and future writes) can surface a precise "your date
  /// is malformed" toast instead of the generic JSON schema rejection text.
  const factory BridgeError.invalidDate(String field0) =
      BridgeError_InvalidDate;
}
