// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 563171549;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'mivalta_rust_bridge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiBuildSourceOverview({
    required EnginesHandle handle,
    required String sourcesJson,
  });

  Future<String> crateApiClassifySource({
    required EnginesHandle handle,
    required String source,
  });

  Future<EnginesHandle> crateApiConstructEngines({
    required String athleteProfileJson,
    required String tablesJson,
    required String vaultPath,
  });

  Future<EnginesHandle> crateApiConstructEnginesFresh({
    required String athleteProfileJson,
    required String tablesJson,
    required String vaultPath,
  });

  Future<EnginesHandle> crateApiConstructEnginesFromState({
    required String athleteProfileJson,
    required String tablesJson,
    required String vaultPath,
    required String viterbiStateJson,
  });

  Future<String> crateApiEngineHello();

  Future<String> crateApiGetContextWidget({required EnginesHandle handle});

  Future<String> crateApiGetDashboard({required EnginesHandle handle});

  Future<String> crateApiGetSessionWidget({required EnginesHandle handle});

  Future<String> crateApiGetStateWidget({required EnginesHandle handle});

  Future<bool> crateApiHasPersistedState({
    required String athleteProfileJson,
    required String vaultPath,
  });

  Future<String> crateApiLastObservationSourceTier({
    required EnginesHandle handle,
  });

  Future<String> crateApiNormalizeObservation({
    required EnginesHandle handle,
    required String vendor,
    required String json,
  });

  Future<String?> crateApiReadPersistedState({
    required String athleteProfileJson,
    required String vaultPath,
  });

  Future<String> crateApiReadReadinessHistory({
    required EnginesHandle handle,
    required int days,
  });

  Future<String> crateApiReadViterbiState({required EnginesHandle handle});

  Future<String> crateApiReadinessIndicator({required EnginesHandle handle});

  Future<String> crateApiReadinessScore({required EnginesHandle handle});

  Future<String> crateApiRecommendWorkout({required EnginesHandle handle});

  Future<String> crateApiSaveState({required EnginesHandle handle});

  Future<String> crateApiVaultSnapshot({required EnginesHandle handle});

  Future<String> crateApiViterbiFatigueState({required EnginesHandle handle});

  Future<void> crateApiWriteMinimalBiometric({
    required EnginesHandle handle,
    required String source,
    required String isoDate,
    required int restingHr,
  });

  Future<void> crateApiWriteViterbiState({
    required EnginesHandle handle,
    required String stateJson,
  });

  Future<String> crateApiZoneCapWithAdvisories({required EnginesHandle handle});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_EnginesHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_EnginesHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_EnginesHandlePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiBuildSourceOverview({
    required EnginesHandle handle,
    required String sourcesJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
            handle,
            serializer,
          );
          sse_encode_String(sourcesJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiBuildSourceOverviewConstMeta,
        argValues: [handle, sourcesJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBuildSourceOverviewConstMeta =>
      const TaskConstMeta(
        debugName: "build_source_overview",
        argNames: ["handle", "sourcesJson"],
      );

  @override
  Future<String> crateApiClassifySource({
    required EnginesHandle handle,
    required String source,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
            handle,
            serializer,
          );
          sse_encode_String(source, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiClassifySourceConstMeta,
        argValues: [handle, source],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClassifySourceConstMeta => const TaskConstMeta(
    debugName: "classify_source",
    argNames: ["handle", "source"],
  );

  @override
  Future<EnginesHandle> crateApiConstructEngines({
    required String athleteProfileJson,
    required String tablesJson,
    required String vaultPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(athleteProfileJson, serializer);
          sse_encode_String(tablesJson, serializer);
          sse_encode_String(vaultPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiConstructEnginesConstMeta,
        argValues: [athleteProfileJson, tablesJson, vaultPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConstructEnginesConstMeta => const TaskConstMeta(
    debugName: "construct_engines",
    argNames: ["athleteProfileJson", "tablesJson", "vaultPath"],
  );

  @override
  Future<EnginesHandle> crateApiConstructEnginesFresh({
    required String athleteProfileJson,
    required String tablesJson,
    required String vaultPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(athleteProfileJson, serializer);
          sse_encode_String(tablesJson, serializer);
          sse_encode_String(vaultPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiConstructEnginesFreshConstMeta,
        argValues: [athleteProfileJson, tablesJson, vaultPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConstructEnginesFreshConstMeta =>
      const TaskConstMeta(
        debugName: "construct_engines_fresh",
        argNames: ["athleteProfileJson", "tablesJson", "vaultPath"],
      );

  @override
  Future<EnginesHandle> crateApiConstructEnginesFromState({
    required String athleteProfileJson,
    required String tablesJson,
    required String vaultPath,
    required String viterbiStateJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(athleteProfileJson, serializer);
          sse_encode_String(tablesJson, serializer);
          sse_encode_String(vaultPath, serializer);
          sse_encode_String(viterbiStateJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiConstructEnginesFromStateConstMeta,
        argValues: [
          athleteProfileJson,
          tablesJson,
          vaultPath,
          viterbiStateJson,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConstructEnginesFromStateConstMeta =>
      const TaskConstMeta(
        debugName: "construct_engines_from_state",
        argNames: [
          "athleteProfileJson",
          "tablesJson",
          "vaultPath",
          "viterbiStateJson",
        ],
      );

  @override
  Future<String> crateApiEngineHello() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineHelloConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineHelloConstMeta =>
      const TaskConstMeta(debugName: "engine_hello", argNames: []);

  @override
  Future<String> crateApiGetContextWidget({required EnginesHandle handle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
            handle,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiGetContextWidgetConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetContextWidgetConstMeta => const TaskConstMeta(
    debugName: "get_context_widget",
    argNames: ["handle"],
  );

  @override
  Future<String> crateApiGetDashboard({required EnginesHandle handle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
            handle,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiGetDashboardConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetDashboardConstMeta =>
      const TaskConstMeta(debugName: "get_dashboard", argNames: ["handle"]);

  @override
  Future<String> crateApiGetSessionWidget({required EnginesHandle handle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
            handle,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiGetSessionWidgetConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetSessionWidgetConstMeta => const TaskConstMeta(
    debugName: "get_session_widget",
    argNames: ["handle"],
  );

  @override
  Future<String> crateApiGetStateWidget({required EnginesHandle handle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
            handle,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiGetStateWidgetConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetStateWidgetConstMeta =>
      const TaskConstMeta(debugName: "get_state_widget", argNames: ["handle"]);

  @override
  Future<bool> crateApiHasPersistedState({
    required String athleteProfileJson,
    required String vaultPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(athleteProfileJson, serializer);
          sse_encode_String(vaultPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiHasPersistedStateConstMeta,
        argValues: [athleteProfileJson, vaultPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHasPersistedStateConstMeta => const TaskConstMeta(
    debugName: "has_persisted_state",
    argNames: ["athleteProfileJson", "vaultPath"],
  );

  @override
  Future<String> crateApiLastObservationSourceTier({
    required EnginesHandle handle,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
            handle,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiLastObservationSourceTierConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLastObservationSourceTierConstMeta =>
      const TaskConstMeta(
        debugName: "last_observation_source_tier",
        argNames: ["handle"],
      );

  @override
  Future<String> crateApiNormalizeObservation({
    required EnginesHandle handle,
    required String vendor,
    required String json,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
            handle,
            serializer,
          );
          sse_encode_String(vendor, serializer);
          sse_encode_String(json, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiNormalizeObservationConstMeta,
        argValues: [handle, vendor, json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNormalizeObservationConstMeta =>
      const TaskConstMeta(
        debugName: "normalize_observation",
        argNames: ["handle", "vendor", "json"],
      );

  @override
  Future<String?> crateApiReadPersistedState({
    required String athleteProfileJson,
    required String vaultPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(athleteProfileJson, serializer);
          sse_encode_String(vaultPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiReadPersistedStateConstMeta,
        argValues: [athleteProfileJson, vaultPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReadPersistedStateConstMeta => const TaskConstMeta(
    debugName: "read_persisted_state",
    argNames: ["athleteProfileJson", "vaultPath"],
  );

  @override
  Future<String> crateApiReadReadinessHistory({
    required EnginesHandle handle,
    required int days,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
            handle,
            serializer,
          );
          sse_encode_i_32(days, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiReadReadinessHistoryConstMeta,
        argValues: [handle, days],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReadReadinessHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "read_readiness_history",
        argNames: ["handle", "days"],
      );

  @override
  Future<String> crateApiReadViterbiState({required EnginesHandle handle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
            handle,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiReadViterbiStateConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReadViterbiStateConstMeta => const TaskConstMeta(
    debugName: "read_viterbi_state",
    argNames: ["handle"],
  );

  @override
  Future<String> crateApiReadinessIndicator({required EnginesHandle handle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
            handle,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiReadinessIndicatorConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReadinessIndicatorConstMeta => const TaskConstMeta(
    debugName: "readiness_indicator",
    argNames: ["handle"],
  );

  @override
  Future<String> crateApiReadinessScore({required EnginesHandle handle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
            handle,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiReadinessScoreConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReadinessScoreConstMeta =>
      const TaskConstMeta(debugName: "readiness_score", argNames: ["handle"]);

  @override
  Future<String> crateApiRecommendWorkout({required EnginesHandle handle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
            handle,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiRecommendWorkoutConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecommendWorkoutConstMeta =>
      const TaskConstMeta(debugName: "recommend_workout", argNames: ["handle"]);

  @override
  Future<String> crateApiSaveState({required EnginesHandle handle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
            handle,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSaveStateConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSaveStateConstMeta =>
      const TaskConstMeta(debugName: "save_state", argNames: ["handle"]);

  @override
  Future<String> crateApiVaultSnapshot({required EnginesHandle handle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
            handle,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiVaultSnapshotConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultSnapshotConstMeta =>
      const TaskConstMeta(debugName: "vault_snapshot", argNames: ["handle"]);

  @override
  Future<String> crateApiViterbiFatigueState({required EnginesHandle handle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
            handle,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiViterbiFatigueStateConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiViterbiFatigueStateConstMeta =>
      const TaskConstMeta(
        debugName: "viterbi_fatigue_state",
        argNames: ["handle"],
      );

  @override
  Future<void> crateApiWriteMinimalBiometric({
    required EnginesHandle handle,
    required String source,
    required String isoDate,
    required int restingHr,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
            handle,
            serializer,
          );
          sse_encode_String(source, serializer);
          sse_encode_String(isoDate, serializer);
          sse_encode_i_32(restingHr, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiWriteMinimalBiometricConstMeta,
        argValues: [handle, source, isoDate, restingHr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWriteMinimalBiometricConstMeta =>
      const TaskConstMeta(
        debugName: "write_minimal_biometric",
        argNames: ["handle", "source", "isoDate", "restingHr"],
      );

  @override
  Future<void> crateApiWriteViterbiState({
    required EnginesHandle handle,
    required String stateJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
            handle,
            serializer,
          );
          sse_encode_String(stateJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiWriteViterbiStateConstMeta,
        argValues: [handle, stateJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWriteViterbiStateConstMeta => const TaskConstMeta(
    debugName: "write_viterbi_state",
    argNames: ["handle", "stateJson"],
  );

  @override
  Future<String> crateApiZoneCapWithAdvisories({
    required EnginesHandle handle,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
            handle,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiZoneCapWithAdvisoriesConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZoneCapWithAdvisoriesConstMeta =>
      const TaskConstMeta(
        debugName: "zone_cap_with_advisories",
        argNames: ["handle"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_EnginesHandle => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_EnginesHandle => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle;

  @protected
  EnginesHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EnginesHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  EnginesHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EnginesHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  EnginesHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EnginesHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return BridgeError_LibraryNotLoaded();
      case 1:
        return BridgeError_EngineConstructionFailed(dco_decode_String(raw[1]));
      case 2:
        return BridgeError_VaultError(dco_decode_String(raw[1]));
      case 3:
        return BridgeError_InputError(dco_decode_String(raw[1]));
      case 4:
        return BridgeError_StateError(dco_decode_String(raw[1]));
      case 5:
        return BridgeError_RoundTripFailed(dco_decode_String(raw[1]));
      case 6:
        return BridgeError_InvalidDate(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  EnginesHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return EnginesHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  EnginesHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return EnginesHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  EnginesHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return EnginesHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return BridgeError_LibraryNotLoaded();
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return BridgeError_EngineConstructionFailed(var_field0);
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return BridgeError_VaultError(var_field0);
      case 3:
        var var_field0 = sse_decode_String(deserializer);
        return BridgeError_InputError(var_field0);
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return BridgeError_StateError(var_field0);
      case 5:
        var var_field0 = sse_decode_String(deserializer);
        return BridgeError_RoundTripFailed(var_field0);
      case 6:
        var var_field0 = sse_decode_String(deserializer);
        return BridgeError_InvalidDate(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
    EnginesHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as EnginesHandleImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
    EnginesHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as EnginesHandleImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnginesHandle(
    EnginesHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as EnginesHandleImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case BridgeError_LibraryNotLoaded():
        sse_encode_i_32(0, serializer);
      case BridgeError_EngineConstructionFailed(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case BridgeError_VaultError(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case BridgeError_InputError(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_String(field0, serializer);
      case BridgeError_StateError(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
      case BridgeError_RoundTripFailed(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_String(field0, serializer);
      case BridgeError_InvalidDate(field0: final field0):
        sse_encode_i_32(6, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class EnginesHandleImpl extends RustOpaque implements EnginesHandle {
  // Not to be used by end users
  EnginesHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  EnginesHandleImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_EnginesHandle,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_EnginesHandle,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_EnginesHandlePtr,
  );
}
